# Generated by Django 5.2.7 on 2026-05-11 09:59

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("prefer_not_to_say", "Prefer not to say"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.1"))
                        ],
                    ),
                ),
                (
                    "height_cm",
                    models.SmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "fitness_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("athlete", "Athlete"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("goals", models.JSONField(blank=True, default=list)),
                ("equipment", models.JSONField(blank=True, default=list)),
                (
                    "session_duration",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("20_30", "20–30 min"),
                            ("30_45", "30–45 min"),
                            ("45_60", "45–60 min"),
                            ("60_plus", "60+ min"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "training_days_per_week",
                    models.SmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(7),
                        ],
                    ),
                ),
                (
                    "injury_history",
                    models.TextField(blank=True, default="", max_length=300),
                ),
                (
                    "lifestyle_description",
                    models.TextField(blank=True, default="", max_length=500),
                ),
                (
                    "sleep_quality",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("poor", "Poor"),
                            ("average", "Average"),
                            ("good", "Good"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "stress_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
