# Generated by Django 5.2.7 on 2026-04-06 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkoutLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="workout.workout",
                    ),
                ),
            ],
            options={
                "ordering": ["-completed_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutLogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exercise_name", models.CharField(max_length=200)),
                ("exercise_order", models.SmallIntegerField()),
                ("set_order", models.SmallIntegerField()),
                ("info", models.CharField(max_length=200)),
                ("nb_reps_target", models.SmallIntegerField()),
                ("nb_reps_actual", models.SmallIntegerField()),
                (
                    "log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="workout.workoutlog",
                    ),
                ),
            ],
            options={
                "ordering": ["exercise_order", "set_order"],
            },
        ),
    ]
