# Generated by Django 5.2.7 on 2026-04-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0005_setofreps_weight_workoutlogentry_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="setofreps",
            name="info",
            field=models.CharField(
                blank=True,
                help_text="Useful instructions, like weight, intensity, how-to, etc",
                max_length=200,
                null=True,
            ),
        ),
    ]
