# Generated by Django 5.2.7 on 2026-04-15 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0010_alter_setofreps_not_null"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workoutlogentry",
            options={
                "ordering": ["set_of_reps__exercise__order", "set_of_reps__order"]
            },
        ),
        migrations.AlterField(
            model_name="workoutlogentry",
            name="nb_reps_target",
            field=models.SmallIntegerField(
                help_text="The target number of reps target for this set."
            ),
        ),
        migrations.AlterField(
            model_name="workoutlogentry",
            name="set_of_reps",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="log_entries",
                to="workout.setofreps",
            ),
        ),
    ]
