# Generated by Django 5.2.7 on 2026-05-09 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0011_alter_workoutlogentry_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workoutlogentry",
            options={
                "ordering": [
                    "-log__completed_at",
                    "set_of_reps__exercise__order",
                    "set_of_reps__order",
                ]
            },
        ),
    ]
