# Generated by Django 5.2.7 on 2026-05-11 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0012_alter_workoutlogentry_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="WarmupSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exercises_hash", models.CharField(max_length=64)),
                ("suggestions", models.JSONField()),
                ("generated_at", models.DateTimeField(auto_now=True)),
                (
                    "workout",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warmup_suggestion",
                        to="workout.workout",
                    ),
                ),
            ],
        ),
    ]
