# Generated by Django 5.2.7 on 2026-05-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0015_exercise_definition_fk"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="setofreps",
            name="info",
        ),
        migrations.AlterField(
            model_name="workout",
            name="name",
            field=models.CharField(
                help_text="Concise name describing this workout.", max_length=200
            ),
        ),
    ]
