# Generated by Django 5.2.7 on 2026-05-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0016_remove_setofreps_info_alter_workout_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="description",
            field=models.TextField(
                blank=True, help_text="Optional detailed description of the workout."
            ),
        ),
    ]
