# Generated by Django 5.2.7 on 2026-05-14 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0017_workout_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="rest_time_after",
            field=models.SmallIntegerField(
                default=60,
                help_text="In seconds, how much time to rest after this exercise.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(300),
                ],
            ),
        ),
    ]
