# Generated by Django 5.2.7 on 2026-05-14 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0018_exercise_rest_time_after"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workout",
            name="rest_time",
        ),
    ]
