# pull official base image
FROM python:3.13

# set work directory
WORKDIR /usr/src/fastapi

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1


COPY ./requirements.txt .
RUN pip install -r requirements.txt

# copy project
COPY . .
