[pytest]
testpaths = src
python_files = test_*.py *_tests.py tests.py
addopts = --cov=src.auth.services --cov=src.catalog.services --cov=src.users.services --cov=src.workouts.services --cov-report=term-missing