# Generated by Django 5.2.7 on 2026-05-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExerciseDefinition",
            fields=[
                (
                    "slug",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=200)),
                ("category", models.CharField(max_length=50)),
                ("force", models.CharField(blank=True, max_length=20, null=True)),
                ("level", models.CharField(max_length=20)),
                ("mechanic", models.CharField(blank=True, max_length=20, null=True)),
                ("equipment", models.CharField(blank=True, max_length=50, null=True)),
                ("primary_muscles", models.JSONField(default=list)),
                ("secondary_muscles", models.JSONField(default=list)),
                ("instructions", models.JSONField(default=list)),
                ("images", models.JSONField(default=list)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
