[pytest]
DJANGO_SETTINGS_MODULE = project.settings
python_files = test_*.py *_tests.py tests.py
addopts = --reuse-db --nomigrations --cov=workout.services --cov=workout.views --cov=workout.warmup_suggestions_service --cov-report=html --cov-report=term